---
- name: install certbot
  yum:
    name: certbot
    state: installed

- name: put shell script after (re)new certificate
  template:
    src: join_certificate.sh.j2
    dest: /opt/join_certificate.sh
    mode: 0755
    owner: root

- name: get a new certificate
  command: |
    /usr/bin/certbot certonly \
      --standalone \
      -d "{{ host_settings.host_name }}" \
      --non-interactive \
      --agree-tos \
      --email {{ letsencrypt_email }} \
      --http-01-port=8888

- name: join certificate
  command: /opt/join_certificate.sh

- name: set cron
  cron:
    name: update letsencrypt certificate
    minute: 0
    hour: 2
    weekday: 0
    job: |
      certbot renew --tls-sni-01-port=8888 --post-hook "/opt/join_certificate.sh" \
        {% if letsencrypt_update_healthchecksio_token %}&& curl -fsS --retry 3 "https://hc-ping.com/{{ letsencrypt_update_healthchecksio_token }}" > /dev/null{% endif%}
