---
- name: install HAProxy
  yum:
    name: haproxy
    state: installed

- name: enable HAProxy
  systemd:
    name: haproxy
    enabled: yes

- name: create HAProxy settings
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: start haproxy
  systemd:
    name: haproxy
    state: started

- include: certbot.yml

- name: set initialized variables
  set_fact:
    initialized: yes

- name: modify HAProxy settings
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart haproxy
