---
- hosts: front
  vars_files:
    - vars/variables.yml
  roles:
    - ssh
    - yum
    - haproxy
- hosts: cockroach
  vars_files:
    - vars/variables.yml
  roles:
    - ssh
    - yum
    - user
    - cockroach
