---
- name: Create group 'cockroach'
  group:
    name: cockroach
    state: present

- name: Create user 'cockroach'
  user:
    name: cockroach
    state: present
    group: cockroach
    home: /var/lib/cockroach
    system: yes
