---
- name: download and expand package
  unarchive:
    src: "{{ cockroach_download_site }}{{ cockroach_package_name }}.tgz"
    dest: /opt/cockroach/
    remote_src: yes
  become: yes
  become_user: cockroach

- name: copy binary
  copy:
    src: "/opt/cockroach/{{ cockroach_package_name }}/cockroach"
    dest: /usr/local/bin/cockroach
    remote_src: yes

