---
- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    group: cockroach
    owner: cockroach
  with_items:
    - /opt/cockroach
    - /var/lib/cockroach/certs
    - /var/lib/cockroach/.cockroach-certs

- include: install.yml
