---
- name: upload service template
  template:
    src: securecockroachdb.service.j2
    dest: /etc/systemd/system/securecockroachdb.service
  notify:
    - restart cockroach

- name: enable service
  systemd:
    name: securecockroachdb
    enabled: yes
  notify:
    - restart cockroach
