---
- name: upadte yum
  yum:
    name: '*'
    state: latest

- name: create cron
  cron:
    name: update yum packages
    minute: 25
    hour: 1
    job: yum update -y {% if yum_update_healthchecksio_token %}&& curl -fsS --retry 3 "https://hc-ping.com/{{ yum_update_healthchecksio_token }}" > /dev/null{% endif %}
